### ISSUE TITLE
Bug with TagAssign

### ISSUE THREAD

**Issue by rocktavious** [OpsLevel/cli#137]
In out CI pipeline we do

```
opslevel create service tag rails_webapp minimum-test-threshold ${TESTS_RAN} --assign
```

But we end up with 2 tags on the service

```yaml
Key: minimum-test-threshold
Value: 15415
```

Somewhere between v2022.9.19 and 2023.7.19 is a bug that breaks TagAssign calls because the API receives

```
tags"=>[{"key"=>"Key", "value"=>"minimum-test-threshold"}, {"key"=>"Value", "value"=>"15415"}
```

but should actually be

```
tags"=>[{"key"=>"minimum-test-threshold", "value"=>"15415"}
```

It seems in https://github.com/OpsLevel/cli/commit/25703267b32cd7c61b44d6b9ce8ce6129c31977b we changed the signature of opslevel-go `AssignTags` function and this is likely the culprit but we will need to investigate whats causing the problem, ensure we have proper and correct tests, and ensure we fix the problem in the CLI (we might want to double check Terraform too)

**Comment by davidbloss** [comment]
https://github.com/OpsLevel/cli/pull/150
