### ISSUE TITLE
Error: error parsing variable 'owner=platform' | %!w(<nil>)

### ISSUE THREAD

**Issue by rdohms** [OpsLevel/cli#320]
When using one of the examples (or my own query) of the graphQL command, the passing in of `fields` appears to be broken.

```
❯ opslevel graphql -f "owner=platform" -f "tier=tier_1" --paginate -a=".account.services.nodes[]" -q='
query ($endCursor: String, $owner: String!, $tier: String!) {
  account {
    services(first: 1, after: $endCursor, ownerAlias: $owner, tierAlias: $tier) {
      nodes {
        name
        aliases
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}'
Error: error parsing variable 'owner=platform' | %!w(<nil>)
```

**Comment by rocktavious** [comment]
@rdohms can you please provide which version of the CLI you are using?  Thanks

**Comment by rocktavious** [comment]
Thanks @rdohms - I don't see anything sticking out at first glance looking at the code and some of the recent commits to that area.  So i'll throw this over to the engineering team to triage further.

**Comment by davidbloss** [comment]
Hi @rdohms, thank you for raising this bug. The fix has been added to the `main` branch and will be included in our next release 🚀
