### ISSUE TITLE
Add option to disable output of headers

### ISSUE THREAD

**Issue by heydonovan** [OpsLevel/cli#61]
Might be too trivial of a feature to implement, but I'm imagining something similar to `kubectl get services --no-headers` or `helm ls --short`.

For now, I'm just doing something like `opslevel list users | sed '1d'`.

**Comment by rocktavious** [comment]
@heydonovan - I quickly added this before the release we are cutting today. 🎉 
https://github.com/OpsLevel/cli/commit/0920b41dcfec658e23d97b157c5ddc1e93a698bf
