### ISSUE TITLE
View dependencies of a service

### ISSUE THREAD

**Issue by heydonovan** [OpsLevel/cli#62]
We can see them in the UI, even though `dependencies:` is blank in `opslevel.yml`. Is there a way to list those?

**Comment by rocktavious** [comment]
@heydonovan - unfortunately no - the "service dependencies" graphQL is still a bit unstable and under development.  We are waiting till thats gets more love before putting it into the CLI.

**Comment by rocktavious** [comment]
Hey @heydonovan - This has finally made it into the CLI on this release https://github.com/OpsLevel/cli/releases/tag/v2023.5.18
